### PR TITLE
Fix for `onServerSearch` and `labelRenderer`

### PR DESCRIPTION
**Pull request by MichalLauer**
This PR fixes issue mentioned in #664 and replaces #665.

I did not use `eval(...)` as suggested because I found on the internet that it might cause security issues. Because of that, I chose the `window[...]` approach. One notable drawback of this implementation is that the functions that will be used (passed in the `onServerSearch` parameter) must be defined outside of any document.ready statement.
I also updated the docs, NEWS.md and version.

Sorry if the news/version update is overboard - feel free to fix it or LMK and I'll create a new PR :)

Thanks!

### CODE REVIEW

**Comment by pvictor** [comment]
Thanks for this.
Can you not change version number ? Or just the 9000 part, version 0.8.2 hasn't been released on CRAN yet.
Can you put an exemple in `examples/` to demonstrate how to use `onServerSearch` ?

**Comment by MichalLauer** [comment]
Hello @pvictor,

I added example into the `examples/` folder and referenced it in the `R/virtual-select.R`. I also reverted back the version.
If anything else is needed, please, let me know :)

**Comment by pvictor** [comment]
That's perfect, thank you! I will release on CRAN shortly.

**Comment by MichalLauer** [comment]
Awesome, thanks for the collaboration :)

**Pull request merged**
