### PR TITLE
make switchInput themable

### LINKED ISSUE #452: Make switchInput themable
``` r
library(shiny)
library(shinyWidgets)

shiny::shinyOptions(bootstrapTheme = bslib::bs_theme(primary = "#ff0000"))

shinyApp(
  fluidPage(switchInput("si", "switchInput", offStatus = "primary")),
  function(input, output, session) {}
)
```
<sup>Created on 2021-12-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Yields this page:
image

instead of this expected page:
image

This is the current SCSS for Bootstrap 4, that should be used for theming:
https://github.com/Bttstrp/bootstrap-switch/blob/master/src/sass/bootstrap4/bootstrap-switch.scss

### PR DESCRIPTION
**Pull request by AshesITR**
closes #452

Upgraded bootstrap-switch to 3.4 and tested the changes interactively in shinyWidgetsGallery()
devtools::check() also runs fine.

I also added .idea to .gitignore and .Rbuildignore.
.idea contains local PyCharm project settings, similar to .Rproj.user for RStudio.

### CODE REVIEW

**Comment by AshesITR** [comment]
The failing check (ubuntu 16.04) seems unrelated to this PR.

**Comment by pvictor** [comment]
Nice work @AshesITR ! 👍 
Thank you very much!

Victor

**Comment by pvictor** [comment]
I submit to CRAN and forgot to add you in NEWS, sorry :disappointed:

**Comment by andyquinterom** [comment]
This seems to break the switchInput when used with shinydashboard. I will look forward to finding a way to reproduce the error and reply with an issue

**Comment by ncuriale** [comment]
with this change, i am unable to reflect change the button size to "mini". even though data-size in the html is set as mini, the bsswitch classes are undefined. any idea here?
image

````
shinyWidgets::switchInput(inputId` = ns("spread_disabled"),
                                      inline = TRUE,
                                      label = "Spread",
                                      onLabel = 'Disabled',
                                      offLabel = 'Enabled',
                                      onStatus = 'danger',
                                      offStatus = 'primary',
                                      size = "mini", 
                                      value = FALSE)
```

![image](https://user-images.githubusercontent.com/23648811/151838618-13bba0f5-4267-4c15-9cf9-fc76b07186f1.png)

**Comment by AshesITR** [comment]
Can you try on the current master branch, @ncuriale ?
It seems to have been fixed by #464 (we downgraded bsswitch to 3.3.4 from 3.4 in that PR).

If the issue still remains, I recommend opening a new issue with a reproducible example.
cc @pvictor do you know whether #464 made it to CRAN? If not, maybe a minor bugfix release would be nice.

**Comment by ncuriale** [comment]
yep looks like the downgrade solved the problem - the current master branch is working as expected. thanks

**Comment by pvictor** [comment]
Not yet on CRAN! I will submit a release by the end of the week!

**Pull request merged**
