### PR TITLE
Added the input-dollar functionality

### PR DESCRIPTION
**Pull request by srmatth**
I have been working on a variety of shiny apps to be used in business applications, and often needed a place where the user could input a dollar amount.  This was difficult with a shiny textInput as the user is not constrained to only typing numbers and in a numericInput trying to see the value of large numbers is difficult if there are no commas.  So I created this dollarInput widget that acts like a text input on the front end (it dynamically includes a dollar sign at the beginning and commas inside the number, while only allowing the user to input numeric values) but a numeric input on the back end (I modified the getValue method in the javascript binding so that it deletes all commas and dollar signs and parses the integer from the text).  There is a lot of potential with this widget, it doesn't support decimal amounts right now and only works with USD, but I would be more than happy to look into extending it if you think it is something that could be included in shinyWidgets.

### CODE REVIEW

**Comment by pvictor** [comment]
Hi,
Interesting widget ! Maybe a more general `currencyInput` will be interesting (I personally deal more often with euros than dollars :p ). Here's a JS libraries that we can use to do the hard work of formatting and parsing input's values : http://autonumeric.org/.

What do you think ?

Victor

**Comment by srmatth** [comment]
I love it! Always love being able to use what someone else has done.  I've spent a little bit trying to integrate it, unfortunately I'm not as proficient in JS as I would like and I'm having trouble getting the input binding to function properly.  I have tried to follow the format you used in the jquery-knob, but in that example you instantiate it with $(el).knob({...}), but this does not work with the AutoNumeric class.  I have worked a way to instantiate a new AutoNumeric and get it to work on initialization but once the user starts typing I cannot access the number value.  Below is what I currently have for the binding.  I will keep trying to figure it out but any help from someone as accomplished at creating custom shiny widgets as you would be great as well if you can see an easy solution.  Thanks!

```
// initialize the input binding
var dollarInputbinding = new Shiny.InputBinding();

// extend the default input binding
$.extend(dollarInputbinding, {

  find: function(scope) {
    return $(scope).find(".auto-numeric");
  },

  initialize: function(el) {
    var currencySymbol = $(el).data("currency-symbol");
    var currencySymbolPlacement = $(el).data("currency-symbol-placement");
    var decimalCharacter = $(el).data("decimal-character");
    var decimalPlaces = $(el).data("decimal-places");
    var digitalGroupSpacing = $(el).data("digital-group-spacing");
    var digitGroupSeparator = $(el).data("digit-group-separator");

    newEl = new AutoNumeric("#" + el.id, $(el).data("value"), {
      currencySymbol: currencySymbol,
      currencySymbolPlacement: currencySymbolPlacement,
      decimalCharacter: decimalCharacter,
      decimalPlaces: decimalPlaces,
      digitalGroupSpacing: digitalGroupSpacing,
      digitGroupSeparator: digitGroupSeparator
    });

    el.setAttribute("data-value", newEl.getNumber());
  },

  getValue: function(el) {
    var value = $(el).data("value");
    return value;
  },

  subscribe: function(el, callback) {
    $(el).on('keyup.dollarInputBinding input.dollarInputBinding', function(event) {
      el.setAttribute("data-value", newEl.getNumber());
      callback(true);
    });
  }

});

// register the input binding
Shiny.inputBindings.register(dollarInputbinding);

```

**Comment by pvictor** [comment]
Hello,

Great start, yes the AutoNumeric method is a little special, I added a minimal working version in `currencyInput()`, pull then you can re-install to test with:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h2("Currency Input"),
  
  shinyWidgets:::currencyInput("id1", "Euro:", value = 1234, format = "euro"),
  verbatimTextOutput("res1"),
  
  shinyWidgets:::currencyInput("id2", "Dollar:", value = 1234, format = "dollar"),
  verbatimTextOutput("res2")
  
)

server <- function(input, output, session) {
  
  output$res1 <- renderPrint(input$id1)
  output$res2 <- renderPrint(input$id2)
  
}

shinyApp(ui, server)
```

Which gives: 

image

Let me know what you think of it.

In my mind I think we can make two functions:

* `currencyInput()` only with format options to keep it simple, and only allow choices like `euro`, `dollar`, `euroSpace`, or a pre-defined language like `Japanese`, `Swiss`
* `autonumericInput()` with full list of options, like currency symbol, thousand separator ...

There's also percentage or numeric format that can be useful, don't know where to put them.

If you like this implementation, we have to do:

* missing arguments ? maybe `inline` parameter
* update method
* documentation and examples
* tests

**Comment by srmatth** [comment]
I love this solution! Thanks for sharing it and helping me out :) I think that the plan with two different functions sounds great and with what you pushed up I should be well on my way to figuring everything out.  

I think the percentage format and basic numeric format are valuable, and see a couple options for dealing with them: 

- we could rename `currencyInput()` to `formatInput()` and include them in it.  The downside to this is that `formatInput(..., input = "Swiss")` is not very intuitive that it will return a currency input
- we could create a third function `formatInput()` that simply wraps `currencyInput()` so that both can be used without confusion on the user side

Let me know if you think either of those options are viable, and I will work on the functions, tests, and documentation over the next couple weeks, pushing up major milestones and letting you know when I do so they can be checked. Thanks again for your help!

**Comment by srmatth** [comment]
Just pushed up commits with functional `autonumericInput()` and `currencyInput()` functions, including documentation/examples.  Let me know if there are any changes and/or corrections that you see.  I always appreciate feedback! :)  Specifically regarding the number of parameters available in `autonumericInput()`. There are quite a few and maybe it would be better to include just the basic ones and then let the other ones be included as a `...` parameter list.  Let me know what you think. I plan to work on the update functions next and then move on to the tests as I go as well.  

Also when you say including an `inline` parameter, could you clarify what you mean? Thanks so much again for all your help :)

**Comment by pvictor** [comment]
That's great !

Some remarks : 

In `autonumericInput()`, you do not need the `lapply` step for parameters with 

```r
function(x) {
      if (identical(x, TRUE))
        "true"
      else if (identical(x, FALSE))
        "false"
      else x
    }
```

{jsonlite} will do that.

I think we can set all arguments to `NULL` by defaults, then use `dropNulls` to drop those not used by user. But using defaults is not bad since it gives a hint to user about what to use...

In JS bindings you don't have to specify each argument, you can use : 

```js
new AutoNumeric(el, config}
```

I think that might be possible to only have one binding, 

In R we can do : 

```r
jsonlite::toJSON(
  x = dropNulls(
    list(
      format = format, # from currencyInput(), NULL in autonumericInput()
      options = list(
        # all arguments from autonumericInput()
      )
    )
  ),
  auto_unbox = TRUE,
  json_verbatim = TRUE
)
```

Then in JS (in init method) : 

```js
if (config.hasOwnProperty("format")) {
  this[el.id] = new AutoNumeric(el, config.format);
} else {
  this[el.id] = new AutoNumeric(el, config.options);
}
```

What do you think ?

Great work again, like it

**Comment by pvictor** [comment]
For the `inline` argument, I thought there was one in `numericInput` but no, my bad

**Comment by srmatth** [comment]
Just pushed up what I think should be the first version that could be considered a "final" version of the functions.  

I thought the 50 arguments for Autonumeric seemed a little overwhelming so I chose what I thought were the top 12 and then added a `...` parameter and included information about other arguments in the documentation, that way more advanced users can still access them while those who don't want to don't have to worry about all those arguments.  I set all arguments to `NULL` but I detail the defaults and possible options in the documentation.  I used dropNulls in the options list that I pass to the javascript side.

I added and update method for each input, and also added `formatNumericInput()` and `updateFormatNumericInput()` which just wrap `currencyInput()` and `updateCurrencyInput()` but are more intuitive for percentage and formatted numbers.

In the binding I made one binding that works for all functions using your suggestions, which cleans it up quite a bit. :) Thanks
I also added functionality to the receive message function so that the update* functions work as they should.

Documentation is up to date, examples have been added in the examples folder under "currencyInput.R" and "autonumericInput.R".

Look it over, let me know what needs to change but I think we are getting close on this! Thanks again for all of your help and for working with me on this!

**Comment by pvictor** [comment]
Merged! 🎉  Thank you, very nice work.
I added your name in DESCRIPTION

**Comment by srmatth** [comment]
Thanks so much! You're the best! 👍🏻

**Pull request merged**
