### PR TITLE
customs sliderInput skins and custom sliderInput colors

### PR DESCRIPTION
**Pull request by DivadNojnarg**
Hi Victor.

My pull request with 2 tiny functions to customize sliderInput:

`setSliderColor` works for any sliders. 
`chooseSliderSkin` apply a global theme for ALL sliders (not possible to separate each slider individually, at the moment)

Cheers

David

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
maybe we could add an example using the 2 new functions such as:

```{r}
if (interactive()) {
  
  library(shiny)
  library(shinyWidgets)
  
  ui <- fluidPage(
    
    setSliderColor(c("YellowGreen ", "#EE82EE"), c(1, 2)),
    chooseSliderSkin("Flat"),
    sliderInput("obs", "Number of observations:",
                min = 0, max = 1000, value = 500
    ),
    sliderInput("obs2", "Number of observations:",
                min = 0, max = 1000, value = 500
    ),
    plotOutput("distPlot")
  )
  
  server <- function(input, output) {
    
    output$distPlot <- renderPlot({
      hist(rnorm(input$obs))
    })
  }
  
  shinyApp(ui, server)
  
}
```

**Comment by pvictor** [comment]
Thanks David ! Sorry for the delay...
No worries for `stopifnot(color %in% w3schools)` since users can specify color in hex format.
I've an idea to match sliders' id to colors, I keep you posted!

Victor

**Comment by pvictor** [comment]
I cited you in news file & change your role in the package description from contributor to author :)

**Comment by DivadNojnarg** [comment]
Thanks Victor! Looking forward to seeing your idea.

**Comment by pvictor** [comment]
Hello David,

I added an argument `color` to `chooseSliderSkin` to change color of all sliders in an app in same time as the skin. It works fine for Modern, HTML5 and Shiny, it's only CSS, but it's more difficult for the others...
For example, Flat skin is based on an image, and that's tricky to modify color of an image : 


Check this example : 

````r



library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  # use Flat design & custom color
  chooseSliderSkin("Modern", color = "#112446"), # 112446 509E2F ed5565
  sliderInput("obs", "Customized single slider:",
              min = 0, max = 100, value = 50
  ),
  sliderInput("obs2", "Customized range slider:",
              min = 0, max = 100, value = c(40, 80)
  ),
  sliderInput("obs3", "An other slider:",
              min = 0, max = 100, value = 50
  ),
  plotOutput("distPlot")
)

server <- function(input, output) {
  
  output$distPlot <- renderPlot({
    hist(rnorm(input$obs))
  })
}

shinyApp(ui, server)
```

With Flat skin, color is a little off...

```r



library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  # use Flat design & custom color
  chooseSliderSkin("Flat", color = "#112446"), # 112446 509E2F ed5565
  sliderInput("obs", "Customized single slider:",
              min = 0, max = 100, value = 50
  ),
  sliderInput("obs2", "Customized range slider1:",
              min = 0, max = 100, value = c(40, 80)
  ),
  sliderInput("obs3", "An other slider:",
              min = 0, max = 100, value = 50
  ),
  plotOutput("distPlot")
)

server <- function(input, output) {
  
  output$distPlot <- renderPlot({
    hist(rnorm(input$obs))
  })
}

shinyApp(ui, server)
```

Victor

**Comment by micahwilhelm** [comment]
May I ask why setSliderColor() was depreciated? It was super useful.

**Pull request merged**
