### PR TITLE
Upgrade ubuntu version in GHA to 18.04

### LINKED ISSUE #456: Ubuntu 16.04 used in R CMD check workflow
GitHub Actions no longer supports Ubuntu 16.04 LTS since the end of september.#
I suggest switching to 18.04 instead.

https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

### PR DESCRIPTION
**Pull request by AshesITR**
Fixes #456

### CODE REVIEW

**Comment by pvictor** [comment]
Thanks, indeed the action yaml is quite old.
What doyou think to use the last template https://github.com/r-lib/actions/blob/v2/examples/check-standard.yaml ?
Apparently version numbers are not hard written

Victor

**Comment by AshesITR** [comment]
The difference is that `ubuntu-latest` will be 20.04 instead of 18.04.
18.04 is older than 20.04, so using 18.04 _should_ better ensure backward compatibility.
But I'm not sure this is much of a concern for shinyWidgets since it doesn't use any system libraries AFAIK.

Let me know if I should change

**Comment by pvictor** [comment]
I think `ubuntu-latest` is sufficient if it's okay for you

**Comment by AshesITR** [comment]
Of course. I've also upgraded the steps to the latest usethis template while at it.

**Comment by pvictor** [comment]
Thank you @AshesITR ! Really appreciate your contributions!

**Pull request merged**
