### PR TITLE
Fix time zone issue for airDatepickerInput

### PR DESCRIPTION
**Pull request by ericnewkirk**
#322

### CODE REVIEW

**Comment by pvictor** [comment]
Thanks, maybe adding an argument for timezone be worth it

**Comment by ericnewkirk** [comment]
My sense when I put together the reprex in [#322](https://github.com/dreamRs/shinyWidgets/issues/322) was that the noise came from differing behavior in `as.Date` and `as.POSIXct`. From `?as.Date`:

> The as.Date methods accept character strings, factors, logical NA and objects of classes "POSIXlt" and "POSIXct". (The last is converted to days by ignoring the time after midnight in the representation of the time in specified time zone, default UTC.)

POSIXct requires a time zone and defaults to the system time zone, so converting back and forth can cause the date to "shift" because of the different defaults. Using `Sys.timezone()` and `as.character()` just ensures that conversions to Date and POSIXct use the same default behavior, so the date value in question can be converted back and forth without changing.

Using a timezone argument might be a more robust way to fix it, but it could also get complicated if the the server and client time zones aren't the same. I suggested changing the behavior within `updateAirDateInput` to try to avoid that, but I don't have a great way to test how it would act if R is running in a different time zone than the browser.

**Comment by pvictor** [comment]
Thanks @ericnewkirk , we are going to use your solution as it is better than mine, this should correct some problems.

Best,

Victor

**Comment by pvictor** [comment]
Close https://github.com/dreamRs/shinyWidgets/issues/322

**Comment by ericnewkirk** [comment]
Thanks @pvictor - I'm not sure "better" is how I'd describe it but I'll take it! Hope it helps.

**Pull request merged**
