### PR TITLE
added numericRange input

### PR DESCRIPTION
**Pull request by wkdavis**
This is a type of input that some of my colleagues requested for a dashboard which I could not find elsewhere. It has been brought up on StackOverflow as well (https://stackoverflow.com/questions/49395482/non-slider-numeric-range-input). While the sliders are aesthetically pleasing, a pair of input boxes are often more efficient and user-friendly. When I first built the dashboard I created 2 separate `numericInput()` objects with ID's "_min" and "_max" and used CSS to style them into the same HTML object, but I felt a natively paired input object similar to `dateRangeInput()` would be more developer-friendly.

### CODE REVIEW

**Comment by pvictor** [comment]
Hi @wkdavis !
This looks great!
Before merging, can you make those small changes : 

* Remove the call to `library(shinyRange)` in the demo app
* Add a basic example in `numericRangeInput` documentation
* Replace `@importFrom shiny validateCssUnit` by `@importFrom htmltools validateCssUnit` (those are the same function, but the one in htmltools is already imported in the NAMESPACE)

Sorry for the delay in my answer, after those changes, it will be good!

Victor

**Comment by wkdavis** [comment]
Thank you for reviewing, @pvictor ! I have made the changes per your request.

Wil

**Comment by pvictor** [comment]
Thanks @wkdavis !
I added you to DESCRIPTION and updated NEWS !

Best, Victor

**Comment by wkdavis** [comment]
Thank you @pvictor !

**Comment by pvictor** [comment]
On CRAN now !

**Pull request merged**
