### PR TITLE
Added Tooltip v1.0.16 (virtual-select dependency). Closes #673.

### LINKED ISSUE #673: Include the required files for virtualSelect tooltips
Hello,

I've seen you upgraded **virtual-select** yesterday. This version allows to have tooltips for options displaying the text ellipsis, but in order to get these tooltips, there are two required files, namely **tooltip.min.js** and **tooltip.min.css**, that can be downloaded from [here](https://sa-si-dev.github.io/virtual-select/#/?id=download-files). Then the tooltips appear if one sets the option `showValueAsTags=TRUE`.
```r
library(shiny)
library(shinyWidgets)

options <- c(
  "This is short text",
  "This is a longer text",
  "This is a very very very very long text",
  "This is a super ultra pro max very very very very long text"
)

ui <- fluidPage(
  tags$head(
    tags$scrip(src = "tooltip.min.js"),
    tags$link(rel = "stylesheet", href = "tooltip.min.css")
  ),
  titlePanel("Virtual Select Input Example"),

  virtualSelectInput(
    "selected_option", "Select Digital Thread:", choices = options,
    multiple = TRUE,
    showValueAsTags = TRUE),

  textOutput("selected_value")
)

server <- function(input, output, session) {
  output$selected_value <- renderText({
    paste("You selected:", input$selected_option)
  })
}

shinyApp(ui, server)
```

### PR DESCRIPTION
**Pull request by stla**
I also added the option `all_files=FALSE` in `htmlDependency`. I think you should always set this option, otherwise all files in the **packer** folder are included.

### CODE REVIEW

**Comment by pvictor** [comment]
Hi,

Thanks for this. Isn't it possible to include those files directly in the bundle ?
You're right for the all_files arg, i'll put it in the other dependencies.

**Comment by stla** [comment]
> Thanks for this. Isn't it possible to include those files directly in the bundle ? 

I don't know but I don't think so, because there's no such bundle on the download page.

**Comment by pvictor** [comment]
I was thinking of something like : 

```js
import "tooltip-plugin/dist/tooltip.min.css";
import "tooltip-plugin/dist/tooltip.min.js";
```

here : https://github.com/dreamRs/shinyWidgets/blob/master/srcjs/inputs/virtual-select.js

which is the script that generate the one in inst/packer after calling `packer::bundle()`

**Comment by pvictor** [comment]
I've modified the PR accordingly.
Thank you !

**Pull request merged**
