### PR TITLE
feat: add commas in value and total of progressBar

### PR DESCRIPTION
**Pull request by swsoyee**
Feel free to edit this PR : )

### CODE REVIEW

**Comment by swsoyee** [comment]
@pvictor Hi, would you mind checking this PR?

**Comment by pvictor** [comment]
Sure, I understand the progressbar changes but what have you modified in shinyWidgets.css ?

I don't use this file anymore, and neither does uglify.R (I should remove them)

JavaScript (`shinyWidgets-bindings.min.js`) & CSS (`shinyWidgets.min.css`) files are created in ìnst/assets/tools.R

**Comment by swsoyee** [comment]
Thanks, I didn't modify any `shinyWidgets.css`, it's updated by `uglify.R` automatically, so I thought it was caused by forgetting to sync the update (commit in 60e0830). 

> JavaScript (shinyWidgets-bindings.min.js) & CSS (shinyWidgets.min.css) files are created in ìnst/assets/tools.R (note it require this package to execute: https://github.com/dreamRs/jstools)

Thank you for the development suggestions, I will fix these non-essential changes later.

**Comment by pvictor** [comment]
Ok! it was to be sure not to lose any of your modifications

I can merge like that, that's good for me

**Pull request merged**
