### PR TITLE
add setBackgroundColor, setBackgroundImage and useShinydashboardPlus

### PR DESCRIPTION
**Pull request by DivadNojnarg**
Hi Victor,

Let me know if your are interested by these features. `setBackgroundColor` is particularly useful when using your brand new `useShinydashboard` function since it increases box visibility. (I use ghostwrite by default in the example). setBackgroundImage could be nice, if reasonably used.

`useShinydashboard` is a very nice idea. Therefore I added useShinydashboardPlus ;), so that user can take advantage of some extra functions such as boxPlus ...

Cheers

David

### CODE REVIEW

**Comment by pvictor** [comment]
Thanks David! Nice additions!
All good for me me, I merge.

Victor

**Comment by pvictor** [comment]
Hi David:
Your function `setBackgroundColor` gave me some ideas :)
I added an option to set a gradient color background if more than one color is used, check this example : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(

  # use a graddient in background
  setBackgroundColor(
    color = c("#F7FBFF", "#2171B5"),
    gradient = "linear",
    direction = "bottom"
  ),

  titlePanel("Hello Shiny!"),

  sidebarLayout(

    sidebarPanel(
      sliderInput("obs",
                  "Number of observations:",
                  min = 0,
                  max = 1000,
                  value = 500)
    ),

    mainPanel(
      plotOutput("distPlot")
    )
  )
)

server <- function(input, output, session) {

  output$distPlot <- renderPlot({
    hist(rnorm(input$obs))
  })

}

shinyApp(ui, server)
```

Victor

**Comment by DivadNojnarg** [comment]
Hi Victor,

Very nice! I think users will really appreciate it. For the setBackgroundImage, if you have time, it would be nice to add the an opacity option.

Cheers and have a nice weekend (soon)

David


Granjon David
PhD
The Interface Group
*
University of Zürich
Institute of Physiology
Winterthurerstr. 190, Y23 J 78
8057 Zürich
+41 (0) 44 635 50 56
https://divadnojnarg.github.io <https://divadnojnarg.github.io/>

**Comment by DivadNojnarg** [comment]
Hi Victor,

There is something I missed with GitHub: how would I do to update my own fork of shinyWidgets? Each time you make a change in the master, I use git pull but everything is up to date so I cannot download your recent changes. Maybe I forgot something during the configuration.

Thanks.

Cheers

David

Granjon David
PhD
The Interface Group
*
University of Zürich
Institute of Physiology
Winterthurerstr. 190, Y23 J 78
8057 Zürich
+41 (0) 44 635 50 56
https://divadnojnarg.github.io <https://divadnojnarg.github.io/>

**Comment by pvictor** [comment]
I think you can do : 

```
git pull upstream master
git push origin master
```

This link can be helpful too : https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by DivadNojnarg** [comment]
Perfect!

David

Granjon David
PhD
The Interface Group
*
University of Zürich
Institute of Physiology
Winterthurerstr. 190, Y23 J 78
8057 Zürich
+41 (0) 44 635 50 56
https://divadnojnarg.github.io <https://divadnojnarg.github.io/>

**Pull request merged**
