### PR TITLE
fix #196

### LINKED ISSUE #196: sweetalert is not module-friendly
All sweetalert functions wich return an input value (such as `confirmSweetAlert()`) are not module friendly in the sense that `inputId` is used without checking for namespaces.

This causes "naive" programming to not work as expected within modules.

To fix this, the same approach as `shinyjs:::jsFuncHelper` choses is appropriate.
The following code chunk needs to be added to all sweetalert functions which handle an `inputId`:

```r
if (inherits(session, "session_proxy")) {
    inputId <- session$ns(inputId)
}
```

I can cook up a PR with the necessary changes if you want me to?

### PR DESCRIPTION
**Pull request by AshesITR**
I didn't write any tests for the new code because the test harness doesn't appear to work nicely with modules.

Not sure about updates to NEWS.md (feel free to edit this PR).

I locally did a `devtools::test()` and `devtools::check()` run with all green results.

### CODE REVIEW

**Comment by AshesITR** [comment]
@pvictor Did you have time to look at this yet? I've added a `startsWith()` based guard against external `session$ns()` as per your suggestion.

**Comment by pvictor** [comment]
Sorry I didn't... I'm at useR this week and have to prepare my talk :D
`startWith` is a very good idea! Forgot about this function...
I try to merge before Friday!

**Comment by AshesITR** [comment]
Thanks a lot and good luck with your talk!

**Comment by pvictor** [comment]
Thanks @AshesITR !

**Pull request merged**
