### PR TITLE
Update module-selectizeGroup.R

### PR DESCRIPTION
**Pull request by ismirsehregal**
Keep the selection on updating the choices.

Related shiny issue: https://github.com/rstudio/shiny/issues/3553

### CODE REVIEW

**Comment by pvictor** [comment]
Thanks!
Is the second one needed ? we want to clear all selected values in this observer

**Comment by ismirsehregal** [comment]
You are right 🙈.. only the first one is needed.

**Comment by pvictor** [comment]
Thanks!

We could put `server` as argument of the module. It's only useful of there's a lot of choices i think

**Comment by ismirsehregal** [comment]
That would be great!

**Comment by ismirsehregal** [comment]
@pvictor For a [case like this](https://stackoverflow.com/q/70336016/9841389) it might make sense to also make `selected` an argument of the module. What do you think?

**Comment by ismirsehregal** [comment]
In this context it might also make sense to prepare the params list for selectizeGroupUI based on user args via lapply or mapply as done [here](https://stackoverflow.com/questions/70667870/r-shiny-automatically-adding-filters-with-the-names-of-the-columns-and-select/70679505#70679505).

**Comment by pvictor** [comment]
For adding a `selected` argument:
It should be already possible for the UI part, but option `onInitialize` appears to override it, so maybe use `onInitialize` only if `selected` is `NULL`.
In server part, it's more complicated you have to map to the correct ID and what object to use (reactive or not?)

For using a function to prepare the list of parameter:
Maybe if argument `params` is a `data.frame` automatically construct the list of parameters from the columns of this `data.frame`

**Pull request merged**
